markdown: kramdown
theme: minima

topnav_title: Structural dynamics
# this appears on the top navigation bar next to the home button

site_title: Structural dynamics
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

github_editme_path: KratosMultiphysics/Kratos/tree/master/docs/
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.

feedback_email: miguel.maso@upc.edu
# used as a contact email for the Feedback link in the top navigation bar

collections:
  tooltips:
    output: true
# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true

