title: Dynamics
description: A collection of examples of structural dynamics
author: "Miguel Masó"

theme: minima

base_url: /test-pages
repository: miguelmaso/test-pages

# Minima social links
github_username: miguelmaso
linkedin_username: miguel.maso

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/notebooks.md
  - _pages/about.md

include:
    - _pages

exclude: 
    - .gitignore
    - LICENSE
    - README.md