name: Build LaTeX

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.ipynb'
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.ipynb'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Build LaTeX
        run: |
          cp .github/workflows/release.sh release.sh
          bash release.sh
      - name: Gather build artifacts
        run: |
          mkdir build
          mv problems.pdf build/
      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
