name: Build pdf

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.ipynb'
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.ipynb'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Convert to pdf
        id: convert-to-pdf
        uses: closoco/pdflatex-action@v1.0.0
        with:
          texFile: problems.tex
      - name: Gather build artifacts
        run: |
          mkdir build
          mv problems.pdf build/
      - name: Publish to GitHub pages
        if: success() && github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
